install.packages(c("tidyverse",
                   "jsonlite",
                   "lubridate",
                   "scales",
                   "tidytext",
                   "wordcloud",
                   "cld3",
                   "zoo"
                   ))